### PR TITLE
Pain Framework

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Leaving this here for people to consider and discuss to see if it's actually wanted. 

Features: 

- Being hit by MOST things will cause pain. This will cause your character to react to the pain.   
   - Pain naturally decays over time.
   - Pain decays faster if you haven't been hurt for a while.
   - Various simple actions, like sleeping / resting / lying / sitting down, will cause pain to reduce faster. 
   - Added a few chemicals to medical to help assuage pain. Some existing chemicals now also heal or reduce pain taken. 
   - Pain is based on a bodypart by bodypart basis - chest and head can sustain more pain than limbs. 
      - Augmented limbs also sustain less pain in general. 
      - Hurt limbs will be easier to disable with stamina damage.
      - Hurt legs will cause you to limp. 
      - Hurt heads will cause brain damage. 
      - If any limb approaches maximum pain, they will be disabled entirely. 
- Being in pain will cause effects.
   - Low amounts can cause minor stuff, like suttering, dropping things, and stamina damage. 
   - As you gain more and more pain, your movement speed and actions will slow and your mood will worsen.
   - Sustaining very large amounts of pain can cause Shock.
      - Shock can be treated by assuaging the patient's pain and keeping them lying down and calm. 
      - Shock is not inherently lethal, but can cause a heart attack if not treated. 
      - Emergency medkits now contain shock blankets, which help regulate temperature. This is helpful for treating shock. 
      - Emergency medkits also carry very addictive painkilling medipens. 
- Medical vendors now have a few new tools for helping pain.
   - Heat packs and cool packs, which are held to hurt limbs to resolve pain.
      - Frozen objects and beer bottles can also function as ghetto alternatives for cold packs. 
   - Shock blankets (see above). 
   - Painkillers. 
- Cargo now carries prescription drugs - painkillers and antidepressants, primarily. 
- Surgery indicts a large amount of pain. Anesthetic helps stop this.
   - Healium can be used an an anesthetic. 
- Many things now give a modifier to the amount of pain received. 
- Added 3 quirks which interact with the pain system. 
- Salvage crew members have a skillchip that reduces pain when they're off ship. 
   - The QM has extra. 
   - Painkiller medipens can be bought in mining vendors.
   - Legion skulls remove a lot of pain instantly.  
- Adds an admin smite. It causes people to take 100x as much pain.
- Some specific events can cause more pain.
   - Falling multiple z-levels
   - Wing potion 
   - Getting shocked
   - An opioid addiction
- Multiple virus symptoms now interact with pain in some way. 

New / Tweaked Reagents: 

- Cryoxadone now heals pain.
- Morphine now heals pain, and has been buffed ever so slightly, but is more addictive.
- Aspirin. It's bad at treating head pain, good at treating everything else, and also stops fever. Causes mild disgust.
   - 1 part salicylic acid
   - 1 part acetone
   - 1 part oxygen
   - catalyst: sulfuric acid
- Paracetamol. Okay at just about everything, except fevers. Causes less disgust. Good for general painkilling.
   - 1 part phenol
   - 1 part acetone
   - 1 part hydrogen
   - 1 part oxygen
   - 1 part nitric acid
 - Ibuprofen. Good at headaches and fever, worse at everything else. 
   - 1 part propionic acid
      - At below 250 degrees: 
      - 1 part carbon
      - 1 part hydrogen
      - 1 part oxgen
   - 1 part phenol
   - 1 part oxygen
   - 1 part hydrogen
- Aspirin/Paracetamol/caffeine. Has few side effects and heals pain effectively, but causes toxin damage in high dosages. 
   - 1 part aspirin
   - 1 part paracetamol
   - 1 part coffee
   - at above 480 degrees
- Oxycodone. Very good at healing pain, very addictive. 
   - Juice poppies
- Dimenhydrinate. Medicine that helps against nausea. 
   - 1 part diphenhydramine
   - 1 part nitrogen
   - 1 part chlorine
- Ondansetron, another medicine that helps against nausea. Easier to make than Dimnhydrinate but has side effects 
   - 1 part oil
   - 1 part nitrogen
   - 1 part oxygen
- A lot of other chemicals now carry a pain modifier.
   - Miner's salve, Space drugs, all alcohol (painkiller especially), atropine, epinephrine, determination (and its status effect), stimulants, changeling adrenaline, muscle stimulant, Cordiolis Hepatico (Abductor memechem)
  
## Why It's Good For The Game

/shrug

## Changelog

:cl: Melbert
add: Pain
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
We could honestly remove #232 and all the code associated with surgical screaming if this got added

**Comment by Sylphet** [comment]
I like this, sounds great. It gets the host cat seal of approval (pictured below)

image

**Comment by distributivgesetz** [comment]
just out of complete curiosity, do we have a hackmd for this?

**Comment by CRITAWAKETS** [comment]
finally, this system on a server that actually has anasthetic tanks for roboticists

**Comment by DemoCrack** [comment]
Oxycodone my love.

**Comment by distributivgesetz** [comment]
> ~~who do you think I am~~

yeah i wouldnt make one either tbf

**Comment by axelzonvolt** [comment]
> The med vendors contain a bottle of painkillers + you can order shipments of painkiller from cargo + they exist in emergency medkits, so I think it's somewhat covered, however that being said I could definitely add some themed painkillers to the brute and burn kits

Perhaps there should at least be a smaller pill bottle of painkillers in medical storage and a recipe note in pharmacy for making the basic pills to ease frustration for having to shell out 300 credits from a limited vendor stock because someone touched the grilles on deck one?

**Pull request merged**
