### PR TITLE
Ports Synthhumans and IPCs as a chooseable species from Skyrat

### PR DESCRIPTION
**Pull request by distributivgesetz**
## About The Pull Request

WIP

## Why It's Good For The Game

Capitalize on all of the IPC gamers.

## Changelog

:cl:
add: Add Synthhumans and IPCs as roundstart species.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Downvoted :-1:

**Comment by distributivgesetz** [comment]
> Downvoted 👎

seethe mald cope

**Comment by optimumtact** [comment]
https://user-images.githubusercontent.com/2544323/178355428-992f3523-c993-4def-b9eb-f66b0f940266.mov

**Comment by distributivgesetz** [comment]
bwuh

**Comment by Fikou** [comment]
https://user-images.githubusercontent.com/2544323/178355428-992f3523-c993-4def-b9eb-f66b0f940266.mov

**Comment by distributivgesetz** [comment]
i am adding this because of a bet :c

**Pull request closed without merging**
