### PR TITLE
Ports a BUNCH Of Sprite PRs from /tg/station.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Ports the following PRS:
https://github.com/tgstation/tgstation/pull/69134
https://github.com/tgstation/tgstation/pull/69147
https://github.com/tgstation/tgstation/pull/69126
https://github.com/tgstation/tgstation/pull/69109
https://github.com/tgstation/tgstation/pull/69047
https://github.com/tgstation/tgstation/pull/68524
https://github.com/tgstation/tgstation/pull/67606
https://github.com/tgstation/tgstation/pull/67000
https://github.com/tgstation/tgstation/pull/66942
https://github.com/tgstation/tgstation/pull/66779
https://github.com/tgstation/tgstation/pull/66702
https://github.com/tgstation/tgstation/pull/66570
https://github.com/tgstation/tgstation/pull/66557
https://github.com/tgstation/tgstation/pull/66355
https://github.com/tgstation/tgstation/pull/66202

Which all, in part, contain work from the following people (in order of appearance); 
Any%, TetraZeta, PositiveEntropy/Imaginos16, Azlan, Onule, Axietheaxolotl, Thgvr, AdipemDragon, Triiodine, Retlaw34, PacifistDalek, WatlerJe, Zestybastard, and Dragonfruits.

~~Accreditation is important, kids, this is why I hate the aesthetics module so much~~

Does some LIGHT modifications to magboots and tactical medkits, just to edict-ify them. Also begins work on de-aestheticization, though the work is VERY brief and not at ALL as thorough as it should be.

Small preview of what to expect, showing off the Biosuits, Edict Magboots, Tables, and Captain's laser specifically:
image

## Why It's Good For The Game
We're getting rid of r4407 fire helmets and frankly I think that's enough for a speedmerge.

## Changelog

:cl: Any%, TetraZeta, PositiveEntropy/Imaginos16, Azlan, Onule, Axietheaxolotl, Thgvr, AdipemDragon, Triiodine, Retlaw34, PacifistDalek, WatlerJe, Zestybastard, Dragonfruits, unit0016
imageadd: A bunch of clothing, station objects, and tools have received anything from minor touchups to entire redoes.
/:cl:

### CODE REVIEW

**Comment by Sylphet** [comment]
yes, yES
TEAR THE SOUL FROM IT

**Review by Imaginos16 — APPROVED** [review]
59717D28-5FBA-4880-B4E5-09C4AC6369F3

**Review by distributivgesetz — APPROVED** [review]
demodularization PAIN

**Comment by Ebin-Halcyon** [comment]
Oh yo. This looks baller as hell.

**Pull request merged**
